### ISSUE TITLE
How can I import annotations?

### ISSUE THREAD

**Issue by PIjarihd** [SkalskiP/make-sense#222]
I tried to load the existing annotations for YOLO. However, I got the following error.
![image](https://user-images.githubusercontent.com/90297273/148325246-6a4c47af-3822-4d74-abd1-d07be9c6add2.png)
How should I load them. I want to edit the labels (to be more specific, add more labels)

**Comment by SkalskiP** [comment]
Hello @PIjarihd 👋 ! I know the annotation loading process should be more straightforward. This is one of our goals for this year. In the meantime, I will try to help you. From the screenshot, I assume you will be uploading labels in YOLO format.

1. Load images. For the sake of the example, let us assume that the images have the following names:

- `image-001.png`
- `image-002.png`
- `image-003.png`

2. Load annotations. In YOLO format, each image should have an associated annotations file. The name of the annotation file must be the same as the image name, except that the annotation file must have `txt` extension. So in ou example, we would have following annotations files:

- `image-001.txt`
- `image-002.txt`
- `image-003.txt`

In addition, we need to provide one more file - `labels.txt`. This file contains object class names separated by newline characters. Here's an example for COCO dataset:

```
person
bicycle
car
motorcycle
airplane
bus
train
truck
boat
traffic light
fire hydrant
stop sign
parking meter
bench
bird
cat
dog
horse
sheep
cow
elephant
bear
zebra
giraffe
backpack
umbrella
handbag
tie
suitcase
frisbee
skis
snowboard
sports ball
kite
baseball bat
baseball glove
skateboard
surfboard
tennis racket
bottle
wine glass
cup
fork
knife
spoon
bowl
banana
apple
sandwich
orange
broccoli
carrot
hot dog
pizza
donut
cake
chair
couch
potted plant
bed
dining table
toilet
tv
laptop
mouse
remote
keyboard
cell phone
microwave
oven
toaster
sink
refrigerator
book
clock
vase
scissors
teddy bear
hair drier
toothbrush
```

I hope this post allows you to successfully load the labels into the editor. Let me know if you have any more questions.

**Comment by PIjarihd** [comment]
Thank You so much for such a simple and step-wise description. It works.

**Comment by SkalskiP** [comment]
`labels.txt` example: [labels.txt](https://github.com/SkalskiP/make-sense/files/9824406/labels.txt)

**Comment by ElMahdiAboulmanadel** [comment]
When I import the annotations txt files and the labels.txt I get the bboxes fixed in the top left corner. It's supposed to be positioned in their centers. I checked the annotation's txt files and the format was correct. Can you let me know if it's an issue in MakeSense.ai

**Comment by ElMahdiAboulmanadel** [comment]
<img width="1391" alt="Screen Shot 2023-01-05 at 14 46 38" src="https://user-images.githubusercontent.com/84625924/210794674-e4febb2e-be06-4801-b1e9-462c2375df4f.png">
Here's a screenshot of the issue

**Comment by alexHxun** [comment]
It still doesn`t work , can`t import annotation file like 'image-001.txt'

**Comment by tejasri19** [comment]
I too cannot import annotation in txt format. Did you find the solution? @alexHxun @PIjarihd 
@SkalskiP Suggest us to import the existing annotation to edit them
